
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script';./mvnw install -DskipTests=false

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack